### ISSUE TITLE
P8: Failing to read flash at boot with BMC kernel 4.17+

### ISSUE THREAD

**Issue by AlexanderAmelkin** [open-power/hostboot#146]
OpenBMC upgrade from kernel 4.13 to kernel 4.17 brought in commit [d342b6a973af](https://github.com/openbmc/linux/commit/d342b6a973af) that enabled 4B opcodes for mx66l51235f chips used in P8 reference design (at least IBM Palmetto and YADRO VESNIN).

HostBoot code (or is it SBE?) assumes that the PNOR flash chip is in EN4B mode and uses normal READ (0x03) opcode to read it, but supplies 4-byte addresses with that opcode. After the aforementioned commit in BMC, this does not work anymore and P8 hosts using that chip are unable to boot.

See https://github.com/openbmc/openbmc/issues/3358

**Comment by dcrowell77** [comment]
The SBE code has to work on all systems, regardless of who/what is acting as the flash controller.  This is because the code lives inside the processor module and cannot be updated when moved between systems.  Any change here is likely to break other systems.  Therefore the fix cannot come from the SBE side, the BMC needs to revert its behavior to support the existing hardware/firmware design.

The other note here is that the host code doesn't send any opcodes itself.  In P8 we use logic inside the P8 processor to drive the PNOR operations.  The hardware logic gives us a bit that says 'read', I don't see any other options in a quick skim.
